// @vitest-environment jsdom
import { it, expect } from 'vitest';
it('runs bilingual draft demo with screening, section navigation and simulated submission',async()=>{
 document.body.innerHTML='<div id="app"></div>';
 await import('../src/main');
 const click=(selector:string)=>{const el=document.querySelector<HTMLButtonElement>(selector);expect(el,selector).not.toBeNull();el!.click();};
 const choose=(selector:string)=>{const el=document.querySelector<HTMLInputElement>(selector);expect(el,selector).not.toBeNull();el!.checked=true;el!.dispatchEvent(new Event('input',{bubbles:true}));};
 const next=()=>click('#next');
 next();next();next();
 expect(document.querySelector('[role="alert"]')).not.toBeNull();
 choose('[name="adult"][value="yes"]');choose('[name="understands"][value="yes"]');
 next();next();choose('[name="consent"]');next();
 expect(document.querySelector('h1')!.textContent).toContain('Screening');
 next();expect(document.querySelector('[role="alert"]')).not.toBeNull();
 choose('[name="q2"][value="No"]');
 for(const n of [3,4,5])choose('[name="q'+n+'"][value="Yes"]');
 next();expect(document.querySelector('[role="alert"]')!.textContent).toContain('No answer');
 choose('[name="q2"][value="Yes"]');
 click('[data-lang="ms"]');
 expect(document.documentElement.lang).toBe('ms');
 expect(document.querySelector<HTMLInputElement>('[name="q2"][value="Yes"]')!.checked).toBe(true);
 next();
 expect(document.querySelector('h1')!.textContent).toContain('Demografi');
 click('#previous');
 expect(document.querySelector<HTMLInputElement>('[name="q2"][value="Yes"]')!.checked).toBe(true);
 next();next();next();next();next();
 expect(document.querySelectorAll('[data-edit]').length).toBe(5);
 click('[data-edit="0"]');
 expect(document.querySelector<HTMLInputElement>('[name="q2"][value="Yes"]')!.checked).toBe(true);
 next();next();next();next();next();
 click('[data-lang="en"]');
 next();
 await new Promise(resolve=>setTimeout(resolve,0));
 expect(document.querySelector('h1')!.textContent).toContain('Thank you');
 expect(document.querySelector('.id')!.textContent).toMatch(/^SACOM-/);
 next();
 expect(document.querySelector('h1')!.textContent).toContain('A bigger understanding.');
});
