import './styles.css';
import config from './questionnaire.json';
import { anonymousId, completion, eligible, unanswered, DemoRepository, type Language, type Section, type Answers } from './core';
const sections = config.sections as Section[];
const app = document.querySelector<HTMLDivElement>('#app')!;
let language: Language = 'en', step = 0, section = 0, errors: string[] = [], answers: Answers = {};
let adult = '', understands = '', consent = false, consentAt = '', responseId = anonymousId(), submitted = false, submitting = false;
const repository = new DemoRepository();
const t = (en: string, ms: string) => language === 'en' ? en : ms;
const esc = (value: unknown) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const names = () => [t('Welcome','Selamat datang'),t('Participant information','Maklumat peserta'),t('Eligibility','Kelayakan'),t('Informed consent','Persetujuan termaklum'),t('Questionnaire','Soal selidik'),t('Review & submit','Semak & hantar'),t('Thank you','Terima kasih')];
function option(name: string, value: string, label: string, checked: boolean, type = 'radio') { return `<label class="option"><input type="${type}" name="${name}" value="${esc(value)}" ${checked?'checked':''}> <span>${esc(label)}</span></label>`; }
function render(focus = true) {
 document.documentElement.lang = language;
 let content = '';
 if(step === 0) content = `<span class="badge">${t('RESEARCH QUESTIONNAIRE · VERSION 1','SOAL SELIDIK PENYELIDIKAN · VERSI 1')}</span><h1 tabindex="-1">${t('Understanding perspectives. Supporting research.','Memahami perspektif. Menyokong penyelidikan.')}</h1><p>${t('Welcome to SACOM — Social Acceptance of Cannabis/Marijuana. Explore a sample questionnaire designed for a future academic study.','Selamat datang ke SACOM — Social Acceptance of Cannabis/Marijuana. Terokai soal selidik contoh yang direka untuk kajian akademik pada masa hadapan.')}</p><div class="facts"><div class="fact"><strong>${t('3 sections','3 bahagian')}</strong>${t('Sample questions','Soalan contoh')}</div><div class="fact"><strong>${t('Anonymous','Tanpa nama')}</strong>${t('No identifying details','Tiada butiran pengenalan')}</div><div class="fact"><strong>EN / BM</strong>${t('Your language','Bahasa pilihan anda')}</div></div><div class="notice">${t('Prototype only. This is not an approved study or the final SACOM questionnaire. No responses are sent or stored.','Prototaip sahaja. Ini bukan kajian yang diluluskan atau soal selidik SACOM akhir. Tiada respons dihantar atau disimpan.')}</div>`;
 if(step === 1) content = `<h1 tabindex="-1">${names()[1]}</h1><p>${t('This demonstration shows how a future SACOM participant experience could work. All questions are samples and are not a validated research instrument.','Demonstrasi ini menunjukkan pengalaman peserta SACOM pada masa hadapan. Semua soalan ialah contoh dan bukan instrumen penyelidikan yang telah disahkan.')}</p><h2>${t('Your choice, at every step','Pilihan anda pada setiap langkah')}</h2><p>${t('Participation in this demo is voluntary. You can go back, change answers, or leave at any time before submission. Required questions include a “prefer not to answer” option.','Penyertaan dalam demo ini adalah sukarela. Anda boleh kembali, mengubah jawapan atau keluar pada bila-bila masa sebelum penghantaran. Soalan wajib mempunyai pilihan “tidak mahu menjawab”.')}</p><h2>${t('Privacy in this prototype','Privasi dalam prototaip ini')}</h2><p>${t('Do not enter names, contact details, locations, or other identifying information. Answers remain in this browser tab’s memory and are cleared when you refresh or close it. Submission is simulated; there is no database or analytics.','Jangan masukkan nama, butiran hubungan, lokasi atau maklumat pengenalan lain. Jawapan kekal dalam memori tab pelayar ini dan dipadam apabila anda memuat semula atau menutupnya. Penghantaran disimulasikan; tiada pangkalan data atau analitik.')}</p><div class="notice">${t('Before a real study launches, the research team must provide approved study information, eligibility criteria, risks, contacts, and data retention policies.','Sebelum kajian sebenar dilancarkan, pasukan penyelidik mesti menyediakan maklumat kajian, kriteria kelayakan, risiko, butiran hubungan dan dasar penyimpanan data yang diluluskan.')}</div>`;
 if(step === 2) content = `<h1 tabindex="-1">${names()[2]}</h1><p>${t('These are demonstration criteria only, not the final study criteria.','Ini ialah kriteria demonstrasi sahaja, bukan kriteria kajian akhir.')}</p>${[['adult',t('Are you 18 years of age or older?','Adakah anda berumur 18 tahun atau lebih?'),adult],['understands',t('Can you read English or Bahasa Melayu?','Bolehkah anda membaca bahasa Inggeris atau Bahasa Melayu?'),understands]].map(([id,label,value])=>`<fieldset><legend>${label}</legend>${option(id,'yes',t('Yes','Ya'),value==='yes')}${option(id,'no',t('No','Tidak'),value==='no')}</fieldset>`).join('')}${errors.length ? `<p class="error" role="alert">${adult && understands ? t('You do not meet the sample criteria. You can leave this demo or change an incorrect answer.','Anda tidak memenuhi kriteria contoh. Anda boleh keluar daripada demo atau membetulkan jawapan yang tersilap.') : t('Please answer both questions.','Sila jawab kedua-dua soalan.')}</p>`:''}`;
 if(step === 3) content = `<h1 tabindex="-1">${names()[3]}</h1><p>${t('Please acknowledge the following before continuing with the demonstration.','Sila akui perkara berikut sebelum meneruskan demonstrasi.')}</p><ul><li>${t('I have read the participant information.','Saya telah membaca maklumat peserta.')}</li><li>${t('I understand that this is a sample prototype, not an active study.','Saya memahami bahawa ini ialah prototaip contoh, bukan kajian aktif.')}</li><li>${t('I understand that participation is voluntary and no response is stored.','Saya memahami bahawa penyertaan adalah sukarela dan tiada respons disimpan.')}</li></ul>${option('consent','yes',t('I agree to continue with this demonstration.','Saya bersetuju untuk meneruskan demonstrasi ini.'),consent,'checkbox')}${errors.length?`<p class="error" role="alert">${t('Your agreement is required to continue. You may leave without agreeing.','Persetujuan anda diperlukan untuk meneruskan. Anda boleh keluar tanpa bersetuju.')}</p>`:''}`;
 if(step === 4) {const s=sections[section];content=`<div class="progress-meta"><span>${t('Section','Bahagian')} ${section+1} / ${sections.length}</span><span>${completion(sections,answers)}% ${t('of required answers','jawapan wajib')}</span></div><progress max="100" value="${completion(sections,answers)}" aria-label="${t('Required answers completed','Jawapan wajib lengkap')}"></progress><span class="badge">${t('SAMPLE QUESTIONS','SOALAN CONTOH')}</span><h1 tabindex="-1">${s.title[language]}</h1><p>${s.description[language]}</p>${s.questions.map(q=>`<fieldset class="${errors.includes(q.id)?'invalid':''}"><legend>${esc(q.label[language])} <small>${q.required?t('(required)','(wajib)'):t('(optional)','(pilihan)')}</small></legend>${q.type==='textarea'?`<textarea name="${q.id}" maxlength="2000" aria-label="${esc(q.label[language])}" placeholder="${t('Please avoid identifying details.','Sila elakkan butiran pengenalan.')}">${esc(answers[q.id]||'')}</textarea>`:q.options!.map(o=>option(q.id,o.value,o.label[language],Array.isArray(answers[q.id])?(answers[q.id] as string[]).includes(o.value):answers[q.id]===o.value,q.type)).join('')}${errors.includes(q.id)?`<p class="error" role="alert">${t('Please select an answer.','Sila pilih jawapan.')}</p>`:''}</fieldset>`).join('')}`;}
 if(step === 5) content=`<h1 tabindex="-1">${names()[5]}</h1><p>${t('Check your answers before completing this demonstration. You can edit any section.','Semak jawapan anda sebelum melengkapkan demonstrasi ini. Anda boleh mengedit mana-mana bahagian.')}</p>${sections.map((s,i)=>`<div class="review-heading"><h2>${esc(s.title[language])}</h2><button class="link" data-edit="${i}">${t('Edit','Edit')}<span class="sr-only"> — ${esc(s.title[language])}</span></button></div><dl>${s.questions.map(q=>{const a=answers[q.id];const values=Array.isArray(a)?a:a?[a]:[];const label=q.type==='textarea'?a:values.map(v=>q.options?.find(o=>o.value===v)?.label[language]||v).join(', ');return `<div class="review"><dt>${esc(q.label[language])}</dt><dd>${esc(label||t('Not answered','Tidak dijawab'))}</dd></div>`;}).join('')}</dl>`).join('')}<div class="notice">${t('Demo submission only. Your answers will not be saved or sent anywhere.','Penghantaran demo sahaja. Jawapan anda tidak akan disimpan atau dihantar ke mana-mana.')}</div>${errors.length?`<p class="error" role="alert">${t('Submission could not be completed. Please try again.','Penghantaran tidak dapat dilengkapkan. Sila cuba lagi.')}</p>`:''}`;
 if(step === 6) content=`<span class="badge">${t('DEMONSTRATION COMPLETE','DEMONSTRASI SELESAI')}</span><h1 tabindex="-1">${t('Thank you for taking part.','Terima kasih atas penyertaan anda.')}</h1><p>${t('You have completed the SACOM prototype. This submission was simulated; no research response has been stored.','Anda telah melengkapkan prototaip SACOM. Penghantaran ini disimulasikan; tiada respons penyelidikan disimpan.')}</p><p>${t('Your anonymous demo response ID','ID respons demo tanpa nama anda')}</p><div class="id">${esc(responseId)}</div><p>${t('This ID demonstrates how a future response receipt could look.','ID ini menunjukkan contoh resit respons pada masa hadapan.')}</p>`;
 app.innerHTML=`<div class="shell"><header class="header"><div class="brand">SACOM<small>${t('SOCIAL ACCEPTANCE RESEARCH','PENYELIDIKAN PENERIMAAN SOSIAL')}</small></div><div class="language" aria-label="${t('Language','Bahasa')}"><button data-lang="en" aria-pressed="${language==='en'}">English</button><button data-lang="ms" aria-pressed="${language==='ms'}">Bahasa Melayu</button></div></header><div class="layout"><aside class="sidebar"><div class="eyebrow">${t('A space for perspectives','Ruang untuk perspektif')}</div><h2>${t('Every perspective starts with a voice.','Setiap perspektif bermula dengan suara.')}</h2><ol class="steps">${names().map((n,i)=>`<li class="${i===step?'active':''}" ${i===step?'aria-current="step"':''}><span>${i<step?'✓':i+1}</span>${n}</li>`).join('')}</ol><p class="note">${t('Sample prototype · No personal details requested','Prototaip contoh · Tiada butiran peribadi diminta')}</p></aside><main class="card">${content}<div class="nav">${step>0&&step<6?`<button class="secondary" id="previous" ${submitting?'disabled':''}>← ${t('Previous','Sebelumnya')}</button>`:'<span></span>'}<button class="primary" id="next" ${submitting?'disabled':''}>${step===6?t('Start a new demo','Mulakan demo baharu'):step===5?t('Complete demo submission','Lengkapkan penghantaran demo'):step===0?t('Begin questionnaire','Mulakan soal selidik'):t('Continue','Teruskan')} ${step===6?'':'→'}</button></div></main></div><footer>${t('SACOM · Academic research prototype · Sample content only','SACOM · Prototaip penyelidikan akademik · Kandungan contoh sahaja')}</footer></div>`;
 app.querySelectorAll<HTMLButtonElement>('[data-lang]').forEach(b=>b.onclick=()=>{language=b.dataset.lang as Language;render(false);});
 app.querySelectorAll<HTMLButtonElement>('[data-edit]').forEach(b=>b.onclick=()=>{section=Number(b.dataset.edit);step=4;errors=[];render();});
 app.querySelector('#previous')?.addEventListener('click',()=>{errors=[];if(step===4&&section>0)section--;else step--;render();});
 app.querySelector('#next')?.addEventListener('click',()=>void next());
 app.querySelectorAll<HTMLInputElement|HTMLTextAreaElement>('input,textarea').forEach(input=>input.addEventListener('input',()=>{
 if(input.name==='adult')adult=input.value;else if(input.name==='understands')understands=input.value;else if(input.name==='consent')consent=(input as HTMLInputElement).checked;
 else {answers[input.name]=input.type==='checkbox'?Array.from(app.querySelectorAll<HTMLInputElement>(`input[name="${input.name}"]:checked`)).map(i=>i.value):input.value; const progress=app.querySelector('progress');if(progress)progress.value=completion(sections,answers);const meta=app.querySelector('.progress-meta span:last-child');if(meta)meta.textContent=`${completion(sections,answers)}% ${t('of required answers','jawapan wajib')}`;}
 }));
 if(focus) app.querySelector<HTMLElement>('h1')?.focus();
}
async function next(){
 errors=[];
 if(step===2&&!eligible(adult,understands)){errors=['eligibility'];render();return;}
 if(step===3){if(!consent){errors=['consent'];render();return;}consentAt=new Date().toISOString();}
 if(step===4){errors=unanswered(sections[section].questions,answers);if(errors.length){render();return;}if(section<sections.length-1){section++;render();return;}}
 if(step===5){if(submitted||submitting)return;const missing=sections.findIndex(s=>unanswered(s.questions,answers).length>0);if(missing>=0){section=missing;step=4;errors=unanswered(sections[missing].questions,answers);render();return;}submitting=true;render(false);try{await repository.submit({responseId,questionnaireVersion:config.version,language,consent:{accepted:true,acceptedAt:consentAt},answers:structuredClone(answers),submittedAt:new Date().toISOString()});submitted=true;answers={};}catch{errors=['submit'];submitting=false;render();return;}submitting=false;}
 if(step===6){step=0;section=0;answers={};adult='';understands='';consent=false;consentAt='';submitted=false;responseId=anonymousId();render();return;}
 step++;render();
}
render(false);
